name: Get Current Time

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Current Time
        id: time
        uses: ./.github/actions/current-time
        with:
          format: 'yyyy-mmm-ddd HH:MM:ss'
      - name: Print Current Time
        run: |
          echo "The current time is ${{ steps.time.outputs.time }}"