name: Test Dice Roll Action

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: actions/dice-roll
    steps:
      - uses: actions/checkout@v2
      - name: install action
        run: |
          npm install
      - name: Dice Roll
        id: dice
        uses: ./actions/dice-roll
        with:
          sides: 6
      - name: Print Dice Roll
        run: |
          echo "The dice roll is ${{ steps.dice.outputs.roll }}"