name: Release Dice Roll Action

on:
  push:

jobs:

  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: actions/dice-roll
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Release
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}