name: Release Current Time Action

on:
  push:

jobs:

  release:
    runs-on: ubuntu-latest
    env:
        working-directory: actions/current-time
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}