name: Test Dice Roll Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dice Roll
        id: dice
        uses: tdupoiron-github-demo/releasing-actions/actions/dice-roll@dice-roll-v1.0.0
        with:
          sides: 6
      - name: Print Dice Roll
        run: |
          echo "The dice roll is ${{ steps.dice.outputs.roll }}"